from __future__ import annotations

import json
import math
import re
import uuid
from dataclasses import dataclass
from pathlib import Path

from agent_kicad.models import CircuitGraph, ComponentSpec
from agent_kicad.sexpr import SExpr, children, first_child, parse_sexpr

SCHEMATIC_VERSION = 20230409
GENERATOR = "agent-kicad"
UUID_NAMESPACE = uuid.UUID("7f54f571-ef8d-5b66-9e99-1ce9e7f20bc9")


@dataclass(frozen=True)
class PinGeometry:
    number: str
    x: float
    y: float
    angle: int


@dataclass(frozen=True)
class SymbolBundle:
    lib_id: str
    library: str
    name: str
    embedded_texts: list[str]
    pins: dict[str, PinGeometry]


def emit_kicad_schematic_project(
    graph: CircuitGraph,
    out_dir: Path,
    symbols_dir: Path,
) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    project_name = graph.project.name
    project_path = out_dir / f"{project_name}.kicad_pro"
    schematic_path = out_dir / f"{project_name}.kicad_sch"
    bundles = _load_symbol_bundles(graph, symbols_dir)
    project_path.write_text(_render_project(project_name), encoding="utf-8")
    schematic_path.write_text(
        _render_schematic(graph, bundles) + "\n", encoding="utf-8"
    )
    return project_path, schematic_path


def _render_project(project_name: str) -> str:
    # KiCad tolerates sparse project files and will fill defaults on save.
    return (
        json.dumps(
            {
                "meta": {"filename": f"{project_name}.kicad_pro", "version": 1},
                "board": {},
                "schematic": {},
            },
            indent=2,
        )
        + "\n"
    )


def _render_schematic(graph: CircuitGraph, bundles: dict[str, SymbolBundle]) -> str:
    root_uuid = _stable_uuid(graph.project.name, "root")
    lines = [
        "(kicad_sch",
        f"  (version {SCHEMATIC_VERSION})",
        f'  (generator "{GENERATOR}")',
        '  (generator_version "0.1.0")',
        f"  (uuid {root_uuid})",
        '  (paper "A4")',
        "  (title_block",
        f'    (title "{_esc(graph.project.name)}")',
        '    (comment 1 "Generated by agent-kicad direct emitter"))',
        "  (lib_symbols",
    ]
    for lib_id in sorted({component.lib_id for component in graph.components}):
        for embedded_text in bundles[lib_id].embedded_texts:
            lines.extend(_indent(embedded_text, 4))
    lines.append("  )")

    placements = _component_placements(graph)
    for component in graph.components:
        lines.extend(
            _render_symbol_instance(
                graph,
                component,
                bundles[component.lib_id],
                placements[component.id],
                root_uuid,
            )
        )

    for net in graph.nets:
        for index, pin in enumerate(net.connections):
            component_xy = placements[pin.component]
            pin_xy = _absolute_pin(
                component_xy, bundles[pin.lib_id].pins[pin.pin_number]
            )
            lines.extend(
                _render_global_label(
                    graph, net.name, pin.component, pin.pin_number, index, pin_xy
                )
            )

    for pin in graph.no_connects:
        component_xy = placements[pin.component]
        pin_xy = _absolute_pin(component_xy, bundles[pin.lib_id].pins[pin.pin_number])
        lines.extend(_render_no_connect(graph, pin.component, pin.pin_number, pin_xy))

    lines.append(")")
    return "\n".join(lines)


def _render_symbol_instance(
    graph: CircuitGraph,
    component: ComponentSpec,
    bundle: SymbolBundle,
    xy: tuple[float, float],
    root_uuid: uuid.UUID,
) -> list[str]:
    x, y = xy
    value = component.value or bundle.name
    lines = [
        "  (symbol",
        f'    (lib_id "{_esc(component.lib_id)}")',
        f"    (at {_fmt(x)} {_fmt(y)} 0)",
        f"    (unit {component.unit})",
        "    (exclude_from_sim no)",
        f"    (in_bom {_yesno(component.in_bom)})",
        f"    (on_board {_yesno(component.on_board)})",
        "    (dnp no)",
        "    (fields_autoplaced yes)",
        f"    (uuid {_stable_uuid(graph.project.name, 'symbol', component.id)})",
    ]
    properties = {
        "Reference": component.id,
        "Value": value,
        "Footprint": component.footprint or "",
        "Datasheet": component.fields.get("Datasheet", "~"),
        **component.fields,
    }
    for name, prop_value in properties.items():
        hidden = name in {"Footprint", "Datasheet"} or name not in {
            "Reference",
            "Value",
        }
        lines.extend(_render_property(name, prop_value, x, y, hidden))
    for pin_number in sorted(bundle.pins, key=_natural_key):
        lines.extend(
            [
                f'    (pin "{_esc(pin_number)}"',
                f"      (uuid {_stable_uuid(graph.project.name, 'pin', component.id, pin_number)}))",
            ]
        )
    lines.extend(
        [
            "    (instances",
            f'      (project "{_esc(graph.project.name)}"',
            f'        (path "/{root_uuid}"',
            f'          (reference "{_esc(component.id)}")',
            f"          (unit {component.unit})))))",
        ]
    )
    return lines


def _render_property(
    name: str, value: str, x: float, y: float, hidden: bool
) -> list[str]:
    lines = [
        f'    (property "{_esc(name)}" "{_esc(value)}"',
        f"      (at {_fmt(x)} {_fmt(y)} 0)",
        "      (effects",
        "        (font",
        "          (size 1.27 1.27))",
    ]
    if hidden:
        lines.append("        (hide yes)")
    lines.extend(["      ))"])
    return lines


def _render_global_label(
    graph: CircuitGraph,
    net_name: str,
    component_id: str,
    pin_number: str,
    index: int,
    xy: tuple[float, float],
) -> list[str]:
    x, y = xy
    return [
        f'  (global_label "{_esc(net_name)}"',
        "    (shape bidirectional)",
        f"    (at {_fmt(x)} {_fmt(y)} 0)",
        "    (effects",
        "      (font",
        "        (size 1.27 1.27))",
        "      (justify left))",
        f"    (uuid {_stable_uuid(graph.project.name, 'label', net_name, component_id, pin_number, str(index))}))",
    ]


def _render_no_connect(
    graph: CircuitGraph,
    component_id: str,
    pin_number: str,
    xy: tuple[float, float],
) -> list[str]:
    x, y = xy
    return [
        "  (no_connect",
        f"    (at {_fmt(x)} {_fmt(y)})",
        f"    (uuid {_stable_uuid(graph.project.name, 'no_connect', component_id, pin_number)}))",
    ]


def _load_symbol_bundles(
    graph: CircuitGraph, symbols_dir: Path
) -> dict[str, SymbolBundle]:
    bundles: dict[str, SymbolBundle] = {}
    for lib_id in sorted({component.lib_id for component in graph.components}):
        library, name = lib_id.split(":", 1)
        path = symbols_dir / f"{library}.kicad_sym"
        text = path.read_text(encoding="utf-8")
        parsed = parse_sexpr(text)
        root = parsed[0]
        exprs = _symbol_exprs(root)
        expr = _resolve_symbol_expr(exprs[name], exprs)
        base_name = _base_symbol_name(name, exprs)
        derived_text = (
            _extract_symbol_block(text, name) if name != base_name else None
        )
        embedded_texts = [
            _symbol_block_for_lib_symbols(
                text, base_name, lib_id, name, derived_text
            )
        ]
        bundles[lib_id] = SymbolBundle(
            lib_id=lib_id,
            library=library,
            name=name,
            embedded_texts=embedded_texts,
            pins=_pin_geometries(expr),
        )
    return bundles


def _symbol_block_for_lib_symbols(
    text: str,
    symbol_name: str,
    lib_id: str | None,
    nested_name: str | None = None,
    derived_text: str | None = None,
) -> str:
    block = _extract_symbol_block(text, symbol_name)
    if lib_id is None:
        return block
    block = re.sub(
        r'^(\s*\(symbol\s+)"[^"]+"',
        rf'\1"{lib_id}"',
        block,
        count=1,
    )
    if nested_name and nested_name != symbol_name:
        block = re.sub(
            rf'(\(symbol\s+)"{re.escape(symbol_name)}([^"]*)"',
            rf'\1"{nested_name}\2"',
            block,
        )
    if derived_text:
        # Merge child symbol's property values over the base's properties.
        # KiCad resolves inherited symbols by keeping the base geometry but
        # overriding properties from the child stub.
        for prop_name, prop_value in re.findall(
            r'\(property\s+"([^"]+)"\s+"([^"]*)"', derived_text
        ):
            block = re.sub(
                rf'(\(property\s+"{re.escape(prop_name)}"\s+)"[^"]*"',
                rf'\1"{prop_value}"',
                block,
                count=1,
            )
    return block


def _symbol_exprs(root: list[SExpr]) -> dict[str, list[SExpr]]:
    exprs: dict[str, list[SExpr]] = {}
    for expr in children(root, "symbol"):
        if len(expr) > 1 and isinstance(expr[1], str):
            exprs[expr[1]] = expr
    return exprs


def _base_symbol_name(symbol_name: str, symbol_exprs: dict[str, list[SExpr]]) -> str:
    current = symbol_name
    seen: set[str] = set()
    while current not in seen and current in symbol_exprs:
        seen.add(current)
        parent = _extends_name(symbol_exprs[current])
        if parent is None:
            break
        current = parent
    return current


def _resolve_symbol_expr(
    expr: list[SExpr],
    symbol_exprs: dict[str, list[SExpr]],
    seen: set[str] | None = None,
) -> list[SExpr]:
    seen = seen or set()
    parent_name = _extends_name(expr)
    if parent_name is None:
        return expr
    if parent_name in seen or parent_name not in symbol_exprs:
        return expr
    parent = _resolve_symbol_expr(
        symbol_exprs[parent_name], symbol_exprs, seen | {parent_name}
    )
    return [*parent, *expr[2:]]


def _extends_name(symbol: list[SExpr]) -> str | None:
    child = first_child(symbol, "extends")
    if child and len(child) > 1 and isinstance(child[1], str):
        return child[1]
    return None


def _extract_symbol_block(text: str, symbol_name: str) -> str:
    match = re.search(rf'(?m)^\s*\(symbol\s+"{re.escape(symbol_name)}"', text)
    if not match:
        raise ValueError(f"symbol not found in library text: {symbol_name}")
    start = match.start()
    depth = 0
    in_string = False
    escape = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]
    raise ValueError(f"unclosed symbol block: {symbol_name}")


def _pin_geometries(symbol: list[SExpr]) -> dict[str, PinGeometry]:
    pins: dict[str, PinGeometry] = {}
    for nested in children(symbol, "symbol"):
        for pin in children(nested, "pin"):
            number = _pin_text(pin, "number")
            at = first_child(pin, "at")
            if number is None or at is None or len(at) < 4:
                continue
            pins[number] = PinGeometry(
                number=number,
                x=float(at[1]),
                y=float(at[2]),
                angle=int(float(at[3])),
            )
    return pins


def _pin_text(pin: list[SExpr], child_name: str) -> str | None:
    child = first_child(pin, child_name)
    if child and len(child) > 1 and isinstance(child[1], str):
        return child[1]
    return None


def _component_placements(graph: CircuitGraph) -> dict[str, tuple[float, float]]:
    placements: dict[str, tuple[float, float]] = {}
    for index, component in enumerate(graph.components):
        if (
            component.placement_hint
            and component.placement_hint.x is not None
            and component.placement_hint.y is not None
        ):
            placements[component.id] = (
                component.placement_hint.x,
                component.placement_hint.y,
            )
            continue
        col = index % 4
        row = index // 4
        placements[component.id] = (101.6 + col * 45.72, 76.2 + row * 35.56)
    return placements


def _absolute_pin(
    component_xy: tuple[float, float], pin: PinGeometry
) -> tuple[float, float]:
    return (component_xy[0] + pin.x, component_xy[1] - pin.y)


def _indent(text: str, spaces: int) -> list[str]:
    prefix = " " * spaces
    return [prefix + line if line else line for line in text.splitlines()]


def _stable_uuid(*parts: str) -> uuid.UUID:
    return uuid.uuid5(UUID_NAMESPACE, ":".join(parts))


def _natural_key(value: str) -> list[int | str]:
    return [int(part) if part.isdigit() else part for part in re.split(r"(\d+)", value)]


def _yesno(value: bool) -> str:
    return "yes" if value else "no"


def _fmt(value: float) -> str:
    if math.isclose(value, round(value), abs_tol=0.000001):
        return str(int(round(value)))
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _esc(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
