from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from agent_kicad.models import CircuitGraph


def emit_skidl_script(
    graph: CircuitGraph,
    output: Path,
    netlist_output: Path | None = None,
    schematic_dir: Path | None = None,
    schematic_top_name: str | None = None,
    symbols_dir: Path | None = None,
    footprints_dir: Path | None = None,
) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    schematic_dir = schematic_dir.resolve() if schematic_dir is not None else None
    output.write_text(
        render_skidl_script(
            graph,
            netlist_output=netlist_output,
            schematic_dir=schematic_dir,
            schematic_top_name=schematic_top_name,
            symbols_dir=symbols_dir,
            footprints_dir=footprints_dir,
        ),
        encoding="utf-8",
    )
    return output


def run_skidl_script(script: Path) -> subprocess.CompletedProcess[str]:
    script = script.resolve()
    cache_dir = script.parent / ".cache"
    env = {
        **os.environ,
        "XDG_DATA_HOME": str(cache_dir / "xdg-data"),
        "XDG_CACHE_HOME": str(cache_dir / "xdg-cache"),
        "MPLCONFIGDIR": str(cache_dir / "matplotlib"),
    }
    return subprocess.run(
        [sys.executable, str(script)],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        cwd=str(script.parent),
        env=env,
    )


def render_skidl_script(
    graph: CircuitGraph,
    netlist_output: Path | None = None,
    schematic_dir: Path | None = None,
    schematic_top_name: str | None = None,
    symbols_dir: Path | None = None,
    footprints_dir: Path | None = None,
) -> str:
    lines = [
        "# Generated by agent-kicad. Edit the connection spec, then regenerate.",
        "import os",
        "from pathlib import Path",
        "",
        "_AGENT_KICAD_CACHE = Path(__file__).resolve().parent / '.cache'",
        "_AGENT_KICAD_HOME = _AGENT_KICAD_CACHE / 'home'",
        "for _version in ('6.0', '7.0', '8.0', '9.0'):",
        "    _fp_table_dir = _AGENT_KICAD_HOME / 'Library/Preferences/kicad' / _version",
        "    _fp_table_dir.mkdir(parents=True, exist_ok=True)",
        "    (_fp_table_dir / 'fp-lib-table').write_text('(fp_lib_table)\\n')",
        "os.environ['HOME'] = str(_AGENT_KICAD_HOME)",
    ]
    if symbols_dir is not None:
        for version in ("", "6", "7", "8", "9"):
            lines.append(
                f"os.environ['KICAD{version}_SYMBOL_DIR'] = {_quote(str(symbols_dir))}"
            )
    if footprints_dir is not None:
        for version in ("", "6", "7", "8", "9"):
            lines.append(
                f"os.environ['KICAD{version}_FOOTPRINT_DIR'] = {_quote(str(footprints_dir))}"
            )
    lines.extend(
        [
            "",
            "from skidl import ERC, KICAD9, Net, Part, generate_netlist, generate_schematic, set_default_tool",
            "import skidl",
            "",
            "set_default_tool(KICAD9)",
        ]
    )
    if symbols_dir is not None:
        lines.append(f"skidl.lib_search_paths[KICAD9] = [{_quote(str(symbols_dir))}]")
    if footprints_dir is not None:
        lines.append(
            f"skidl.footprint_search_paths[KICAD9] = [{_quote(str(footprints_dir))}]"
        )
    lines.extend(["", "parts = {}"])
    for component in graph.components:
        library, name = component.lib_id.split(":", 1)
        lines.append(
            f"parts[{_quote(component.id)}] = Part("
            f"{_quote(library)}, {_quote(name)}, ref={_quote(component.id)}, "
            f"tag={_quote(component.id)})"
        )
        if component.value:
            lines.append(
                f"parts[{_quote(component.id)}].value = {_quote(component.value)}"
            )
        if component.footprint:
            lines.append(
                f"parts[{_quote(component.id)}].footprint = {_quote(component.footprint)}"
            )
        for key, value in sorted(component.fields.items()):
            lines.append(
                f"parts[{_quote(component.id)}].fields[{_quote(key)}] = {_quote(value)}"
            )
        lines.append("")

    lines.append("nets = {}")
    for net in graph.nets:
        lines.append(f"nets[{_quote(net.name)}] = Net({_quote(net.name)})")
        for pin in net.connections:
            lines.append(
                f"nets[{_quote(net.name)}] += "
                f"parts[{_quote(pin.component)}][{_quote(pin.pin_number)}]"
            )
        lines.append("")

    lines.append("ERC()")
    if netlist_output is not None:
        lines.append(_generate_netlist_line(netlist_output))
    if schematic_dir is not None:
        lines.append(
            "generate_schematic("
            f"filepath={_quote(str(schematic_dir))}, "
            f"top_name={_quote(schematic_top_name or graph.project.name)}, "
            f"title={_quote(graph.project.name)}, "
            "flatness=1.0, auto_stub=True"
            ")"
        )
    if netlist_output is None and schematic_dir is None:
        lines.append("generate_netlist(tool=KICAD9)")
    lines.append("")
    return "\n".join(lines)


def render_skidl_manifest(graph: CircuitGraph) -> str:
    payload = {
        "project": graph.project.name,
        "components": [
            {
                "id": component.id,
                "lib_id": component.lib_id,
                "value": component.value,
                "footprint": component.footprint,
            }
            for component in graph.components
        ],
        "nets": [
            {
                "name": net.name,
                "connections": [
                    {
                        "component": pin.component,
                        "pin_number": pin.pin_number,
                        "pin_name": pin.pin_name,
                        "pin_type": pin.pin_type,
                    }
                    for pin in net.connections
                ],
            }
            for net in graph.nets
        ],
    }
    return json.dumps(payload, indent=2)


def _generate_netlist_line(netlist_output: Path | None) -> str:
    if netlist_output is None:
        return "generate_netlist(tool=KICAD9)"
    return f"generate_netlist(file_={_quote(str(netlist_output))}, tool=KICAD9)"


def _quote(value: str) -> str:
    return repr(value)
